[build]
  command = "python -m pip install -r requirements.txt && python app.py"  # Replace with your build command
  publish = "public"  # Set the publish directory

[redirects]
  /* /index.html  # Redirect all routes to index.html for client-side routing
